<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CmsEvents.Application</RootNamespace>
    <AssemblyName>CmsEvents.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CmsEvents.Domain\CmsEvents.Domain.csproj" />
    <ProjectReference Include="..\CmsEvents.Contracts\CmsEvents.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Polly" />
  </ItemGroup>

</Project>
