<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CmsEvents.Integration.Tests</RootNamespace>
    <AssemblyName>CmsEvents.Integration.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CmsEvents.Api\CmsEvents.Api.csproj" />
    <ProjectReference Include="..\..\src\CmsEvents.Application\CmsEvents.Application.csproj" />
    <ProjectReference Include="..\..\src\CmsEvents.Infrastructure\CmsEvents.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CmsEvents.Contracts\CmsEvents.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
